/* eslint-disable */
require('./cancel')
require('./couch')
require('./curtain')
require('./fertilizer')
require('./login')
require('./logout')
require('./moon')
require('./morning')
require('./projector')
require('./soil_moist')
require('./sun')
require('./vacuum')
